# -*- mode: ruby -*-
# vi: set ft=ruby :

# Проверяем наличие плагина "vagrant-reload"
unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed! Please install it and try again.'
end

Vagrant.configure(2) do |config|

  # Скачиваем box для Vagrant
  config.vm.box = "centos/7"
  config.vm.hostname = "centos"

  # config.vm.boot_timeout = 100

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 1500
    v.cpus = 2
    # Set the video memory to 128Mb:
    v.customize ["modifyvm", :id, "--vram", "128"]
    # Enable 3D acceleration:
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  # Устанавливаем связь портов физической и вирутальной машины. 
  # Сайт будет доступен по адресу localhost:8888/ или http://127.0.0.1:8888/
  # Для соединения с базой используйте порт 8889
  # config.vm.network "private_network", ip: "10.110.0.10"
  config.vm.network :forwarded_port, guest: 80, host: 8888, auto_correct: true
  config.vm.network :forwarded_port, guest: 3306, host: 8889, auto_correct: true
  config.vm.network :forwarded_port, guest: 5432, host: 5433, auto_correct: true
  
  # Синхронизируем папки на виртуальной и физической машине
  config.vm.synced_folder "../", "/home/bitrix/"

  # Устанавливаем виртуальную машину битрикс
  config.vm.provision :shell, path: "install.bash"
  config.vm.provision :reload
  config.vm.provision :shell, path: "install_after_reload.bash"
  
end
